### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nelix** [macropodhq/webpack-skel#7]
- [x] Remove sass-loader (could replace with an example doc of how to add it for extra education points)
- [x] eslint
- [x] Fix CommonChunks plugin (or more to a more advanced repo? webpack-skel-production? with static html rendering?)
- [x] turn source-maps on by default (explain or link to webpack page which covers build perf)

Do we still want react and react-router?
Other ideas?

**Comment by wolfeidau** [comment]
So the first things I do:

* remove sass
* add the tweaks to build production code

Yeah i would love source maps and CommonChunks!

**Comment by nelix** [comment]
I'll trim it back as much as I can, then add some of those tweaks and common chunks back one by one
